import { assets } from "@/content/assets";
import type { Piece } from "@/types/piece";

export const featuredPieces: Piece[] = [
  {
    slug: "hero-ring-signature",
    category: "Ring",
    name: "Hero Ring Signature",
    headline: "A nocturnal silhouette calibrated for restrained brilliance.",
    material: "18k blackened white gold",
    stone: "Pavé-set white diamonds",
    availabilityMode: "By Appointment",
    heroImage: assets.pieces.heroRing.hero,
    featuredCardImage: assets.pieces.heroRing.featuredCard,
    campaignImage: assets.pieces.heroRing.campaignStillLife,
    onBodyImage: assets.pieces.heroRing.onBody,
    macroImages: [assets.pieces.heroRing.macroBand, assets.pieces.heroRing.macroGemstone],
    gallery: [assets.pieces.heroRing.gallerySideContour, assets.pieces.heroRing.onBody],
  },
  {
    slug: "eclipse-line",
    category: "Necklace",
    name: "Eclipse Line",
    headline: "Graduated brilliance in a restrained horizon.",
    material: "Platinum",
    stone: "White diamonds",
    availabilityMode: "Limited Series",
    heroImage: assets.pieces.heroRing.campaignStillLife,
    gallery: [assets.pieces.heroRing.gallerySideContour, assets.pieces.heroRing.onBody],
  },
  {
    slug: "velour-cascade",
    category: "Earrings",
    name: "Velour Cascade",
    headline: "Fine motion articulated with vertical clarity.",
    material: "18k yellow gold",
    stone: "Champagne diamonds",
    availabilityMode: "By Appointment",
    heroImage: assets.pieces.heroRing.gallerySideContour,
    gallery: [assets.pieces.heroRing.featuredCard, assets.pieces.heroRing.macroGemstone],
  },
  {
    slug: "astral-cuff",
    category: "Bracelet",
    name: "Astral Cuff",
    headline: "A clean architectural cuff with hidden fire.",
    material: "18k rose gold",
    stone: "Baguette diamonds",
    availabilityMode: "Private Commission",
    heroImage: assets.pieces.heroRing.onBody,
    gallery: [assets.pieces.heroRing.macroBand, assets.pieces.heroRing.campaignStillLife],
  },
];
