import { assets } from "@/content/assets";
import type { Piece } from "@/types/piece";

export const featuredPieces: Piece[] = [
  {
    slug: "hero-ring",
    category: "Ring",
    name: "Hero Ring Signature",
    headline: "A nocturnal silhouette calibrated for restrained brilliance.",
    shortDescription: "A signature ring balancing architectural structure with luminous restraint.",
    material: "18k blackened white gold",
    stone: "Pavé-set white diamonds",
    edition: "Maison Signature · Numbered Series",
    availabilityMode: "By Appointment",
    heroImage: assets.pieces.heroRing.hero,
    featuredCardImage: assets.pieces.heroRing.featuredCard,
    campaignImage: assets.pieces.heroRing.campaignStillLife,
    onBodyImage: assets.pieces.heroRing.onBody,
    macroImages: [assets.pieces.heroRing.macroBand, assets.pieces.heroRing.macroGemstone],
    gallery: [assets.pieces.heroRing.gallerySideContour, assets.pieces.heroRing.onBody, assets.pieces.heroRing.campaignStillLife],
    story: [
      "The Hero Ring emerged from an extended study of shadowed profiles and controlled reflections.",
      "Its elevated shoulders are sculpted to concentrate brilliance toward the center while preserving a quiet silhouette on the hand.",
    ],
  },
  {
    slug: "eclipse-line",
    category: "Necklace",
    name: "Eclipse Line",
    headline: "A graduated horizon of diamonds set to follow the collarbone with quiet cadence.",
    shortDescription: "A long necklace built as a restrained line of calibrated brilliance.",
    material: "Platinum with rhodium depth finish",
    stone: "Graduated white diamonds",
    edition: "Limited Series · 12 annual allocations",
    availabilityMode: "Limited Series",
    heroImage: assets.pieces.eclipseLine.hero,
    featuredCardImage: assets.pieces.eclipseLine.featuredCard,
    campaignImage: assets.pieces.eclipseLine.campaignStillLife,
    onBodyImage: assets.pieces.eclipseLine.onBody,
    macroImages: [assets.pieces.eclipseLine.macroBand],
    gallery: [assets.pieces.eclipseLine.campaignStillLife, assets.pieces.eclipseLine.onBody, assets.pieces.eclipseLine.featuredCard, assets.pieces.eclipseLine.macroBand],
    story: [
      "Eclipse Line is articulated in micro-segments that settle naturally along the neckline.",
      "Stone spacing is intentionally irregular by fractions, creating movement in low evening light rather than overt sparkle.",
    ],
  },
  {
    slug: "velour-cascade",
    category: "Earrings",
    name: "Velour Cascade",
    headline: "Vertical earrings composed for fluid movement and controlled shimmer.",
    shortDescription: "A lightweight pair that translates motion into a soft luminous trail.",
    material: "18k yellow gold",
    stone: "Champagne and white diamond mix",
    edition: "Atelier Selection · Seasonal capsule",
    availabilityMode: "By Appointment",
    heroImage: assets.pieces.velourCascade.hero,
    featuredCardImage: assets.pieces.velourCascade.featuredCard,
    campaignImage: assets.pieces.velourCascade.campaignStillLife,
    onBodyImage: assets.pieces.velourCascade.onBody,
    macroImages: [assets.pieces.velourCascade.macroBand],
    gallery: [assets.pieces.velourCascade.onBody, assets.pieces.velourCascade.campaignStillLife, assets.pieces.velourCascade.featuredCard, assets.pieces.velourCascade.macroBand],
    story: [
      "Velour Cascade balances apparent softness with precise vertical architecture.",
      "The terminal stones are weighted to keep alignment through movement, preserving line from salon to evening ceremony.",
    ],
  },
  {
    slug: "astral-cuff",
    category: "Bracelet",
    name: "Astral Cuff",
    headline: "An open architectural cuff where warmth and precision remain in deliberate tension.",
    shortDescription: "A sculptural wrist line with hidden internal comfort and nocturnal fire.",
    material: "18k rose gold with mirror-polished interior",
    stone: "Baguette and pavé diamonds",
    edition: "Private Commission",
    availabilityMode: "Private Commission",
    heroImage: assets.pieces.astralCuff.hero,
    featuredCardImage: assets.pieces.astralCuff.featuredCard,
    campaignImage: assets.pieces.astralCuff.campaignStillLife,
    onBodyImage: assets.pieces.astralCuff.onBody,
    macroImages: [assets.pieces.astralCuff.macroBand],
    gallery: [
      assets.pieces.astralCuff.campaignStillLife,
      assets.pieces.astralCuff.featuredCard,
      assets.pieces.astralCuff.onBody,
    ],
    story: [
      "Astral Cuff was drafted from a single continuous arc, then opened to create breathing space at the wrist.",
      "The diamond channels are inset below the outer edge so the piece reads as pure volume first, brilliance second.",
    ],
  },
];
