import { assets } from "@/content/assets";
import type { Piece } from "@/types/piece";

export const featuredPieces: Piece[] = [
  {
    slug: "hero-ring",
    category: "Ring",
    name: "Hero Ring Signature",
    headline: "A nocturnal silhouette calibrated for restrained brilliance.",
    shortDescription: "A signature ring balancing architectural structure with luminous restraint.",
    material: "18k blackened white gold",
    stone: "Pavé-set white diamonds",
    edition: "Maison Signature · Numbered Series",
    availabilityMode: "By Appointment",
    heroImage: assets.pieces.heroRing.hero,
    featuredCardImage: assets.pieces.heroRing.featuredCard,
    campaignImage: assets.pieces.heroRing.campaignStillLife,
    onBodyImage: assets.pieces.heroRing.onBody,
    macroImages: [assets.pieces.heroRing.macroBand, assets.pieces.heroRing.macroGemstone],
    gallery: [assets.pieces.heroRing.gallerySideContour, assets.pieces.heroRing.onBody, assets.pieces.heroRing.campaignStillLife],
    story: [
      "The Hero Ring emerged from an extended study of shadowed profiles and controlled reflections.",
      "Its elevated shoulders are sculpted to concentrate brilliance toward the center while preserving a quiet silhouette on the hand.",
    ],
  },
  {
    slug: "eclipse-line",
    category: "Necklace",
    name: "Eclipse Line",
    headline: "Graduated brilliance in a restrained horizon.",
    shortDescription: "A long line of calibrated stones arranged with subtle cadence.",
    material: "Platinum",
    stone: "White diamonds",
    edition: "Limited Series",
    availabilityMode: "Limited Series",
    heroImage: assets.pieces.eclipseLine.hero,
    featuredCardImage: assets.pieces.eclipseLine.featuredCard,
    campaignImage: assets.pieces.eclipseLine.campaignStillLife,
    onBodyImage: assets.pieces.eclipseLine.onBody,
    macroImages: [assets.pieces.eclipseLine.macroBand, assets.pieces.eclipseLine.macroGemstone],
    gallery: [assets.pieces.eclipseLine.gallerySideContour, assets.pieces.eclipseLine.onBody, assets.pieces.eclipseLine.campaignStillLife],
    story: ["Each segment is tension-balanced to maintain a fluid line against the collar while preserving stone clarity."]
  },
  {
    slug: "velour-cascade",
    category: "Earrings",
    name: "Velour Cascade",
    headline: "Fine motion articulated with vertical clarity.",
    shortDescription: "Lightweight vertical earrings designed for movement and rhythm.",
    material: "18k yellow gold",
    stone: "Champagne diamonds",
    edition: "Atelier Selection",
    availabilityMode: "By Appointment",
    heroImage: assets.pieces.velourCascade.hero,
    featuredCardImage: assets.pieces.velourCascade.featuredCard,
    campaignImage: assets.pieces.velourCascade.campaignStillLife,
    onBodyImage: assets.pieces.velourCascade.onBody,
    macroImages: [assets.pieces.velourCascade.macroBand, assets.pieces.velourCascade.macroGemstone],
    gallery: [assets.pieces.velourCascade.gallerySideContour, assets.pieces.velourCascade.onBody, assets.pieces.velourCascade.campaignStillLife],
  },
  {
    slug: "astral-cuff",
    category: "Bracelet",
    name: "Astral Cuff",
    headline: "A clean architectural cuff with hidden fire.",
    shortDescription: "An open cuff where geometry and warmth remain in measured tension.",
    material: "18k rose gold",
    stone: "Baguette diamonds",
    edition: "Private Commission",
    availabilityMode: "Private Commission",
    heroImage: assets.pieces.astralCuff.hero,
    featuredCardImage: assets.pieces.astralCuff.featuredCard,
    campaignImage: assets.pieces.astralCuff.campaignStillLife,
    onBodyImage: assets.pieces.astralCuff.onBody,
    macroImages: [assets.pieces.astralCuff.macroBand, assets.pieces.astralCuff.macroGemstone],
    gallery: [assets.pieces.astralCuff.gallerySideContour, assets.pieces.astralCuff.onBody, assets.pieces.astralCuff.campaignStillLife],
  },
];
